CREATE TABLE IF NOT EXISTS Members(
	Member_ID SERIAL PRIMARY KEY,
	Member_Name VARCHAR(100) NOT NULL,
	"Year_of_Membership(YOM)" DATE NOT NULL,
	Contact INT,
	Address TEXT
);

CREATE TABLE IF NOT EXISTS Books(
	Book_ID SERIAL PRIMARY KEY,
	Title VARCHAR(100) NOT NULL,
	Author VARCHAR(100) NOT NULL,
	Genre VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS "Library staff"(
	Librarian_ID SERIAL PRIMARY KEY,
	Staff_name VARCHAR(100) NOT NULL,
	CONTACT CHAR(13) NOT NULL
);

CREATE TABLE IF NOT EXISTS "Book Loan"(
	Loan_date DATE NOT NULL,
	Due_date DATE NOT NULL,
	Return_date DATE NOT NULL,
	Book_ID INT NOT NULL,
	Member_ID INT NOT NULL,
	Staff_ID INT NOT NULL,
	CONSTRAINT fk_b FOREIGN KEY (Book_ID) REFERENCES Books(Book_ID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_m FOREIGN KEY (Member_ID) REFERENCES Members(Member_ID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_s FOREIGN KEY (Staff_ID) REFERENCES "Library staff"(Librarian_ID) ON DELETE CASCADE ON UPDATE CASCADE
	
);

